version: "3.8"

services:
  activemerchant_development:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - RAILS_ENV=development
    env_file:
      - .env.development.local

networks:
  my-network:
